apiVersion: v1
kind: Secret
metadata:
  name: ecom-secrets
type: Opaque
stringData:
  # Paste your real values here. K8s will encrypt them automatically.
  MONGO_URI: "mongodb+srv://your-atlas-uri..."
  TWILIO_ACCOUNT_SID: "your-sid"
  TWILIO_AUTH_TOKEN: "your-token"
  TWILIO_SERVICE_SID: "your-service-sid"